src/UniqueFundraisingEvent/UniqueFundraisingEvent.Web/Pages/Guests/Create.cshtml.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using UniqueFundraisingEvent.Web.Application.Features.Guests.Commands.RegisterGuest;

namespace UniqueFundraisingEvent.Web.Pages.Guests
{
    public class CreateModel : PageModel
    {
        public List<SelectListItem> States = new List<SelectListItem>
        {
            new SelectListItem
            {
                Text = "Reservado",
                Value = "Reservado"
            },
            new SelectListItem
            {
                Text = "Ingresó",
                Value = "Ingresó"
            },
            new SelectListItem
            {
                Text = "Se retiró",
                Value = "Se retiró"
            }
        };

        [BindProperty]
        [Required(ErrorMessage = "El campo Estado es requerido")]
        public string State { get; set; } = "Reservado";

        [BindProperty]
        [Required(ErrorMessage = "El campo Nombre es requerido")]
        public string Name { get; set; } = string.Empty;

        [BindProperty]
        [Required(ErrorMessage = "El campo Apellido es requerido")]
        public string LastName { get; set; } = string.Empty;

        [BindProperty]
        [Required(ErrorMessage = "El campo Correo es requerido")]
        public string Email { get; set; } = string.Empty;

        [BindProperty]
        [Required(ErrorMessage = "El campo Empresa es requerido")]
        public string Company { get; set; } = string.Empty;

        [BindProperty]
        [Required(ErrorMessage = "El campo Cargo es requerido")]
        public string CompanyPosition { get; set; } = string.Empty;

        private readonly IMediator mediator;

        public CreateModel(IMediator mediator)
        {
            this.mediator = mediator;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
                return Page();

            await mediator.Send(new RegisterGuestCommand(Name, LastName, Email, Company, CompanyPosition));

            return RedirectToPage("./Index");
        }
    }
}

src/UniqueFundraisingEvent/UniqueFundraisingEvent.Web/Pages/Guests/EditDonations.cshtml.cs
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UniqueFundraisingEvent.Web.Application.Features.Guests.Commands.UpdateGuestDonation;
using UniqueFundraisingEvent.Web.Application.Features.Guests.Queries.GetGuest;

namespace UniqueFundraisingEvent.Web.Pages.Guests
{
    [Authorize(Roles = "Administrador,Recolector")]
    public class EditDonationsModel : PageModel
    {
        private readonly IMediator _mediator;

        public EditDonationsModel(IMediator mediator)
        {
            _mediator = mediator;
        }

        [BindProperty]
        public GuestDetail GuestDetail { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }

            var guestDetail = await _mediator.Send(new GetGuestQuery(id.Value));
            if (guestDetail is null)
                return NotFound();

            GuestDetail = guestDetail;

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            var vs = ModelState["GuestDetail.DonationAmount"].ValidationState;

            if (vs == Microsoft.AspNetCore.Mvc.ModelBinding.ModelValidationState.Invalid)
                return Page();

            await _mediator.Send(new UpdateGuestDonationCommand(GuestDetail.Id, GuestDetail.DonationAmount));

            return RedirectToPage("./Index");
        }
    }
}

src/UniqueFundraisingEvent/UniqueFundraisingEvent.Web/Pages/Guests/EditStatus.cshtml.cs
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using System.Data;
using UniqueFundraisingEvent.Web.Application.Features.Guests.Commands.UpdateGuestState;
using UniqueFundraisingEvent.Web.Application.Features.Guests.Queries.GetGuest;

namespace UniqueFundraisingEvent.Web.Pages.Guests
{
    [Authorize(Roles = "Administrador,Recepcionista")]
    public class EditStatusModel : PageModel
    {
        public List<SelectListItem> States = new List<SelectListItem>
        {
            new SelectListItem
            {
                Text = "Reservado",
                Value = "Reservado"
            },
            new SelectListItem
            {
                Text = "Ingresó",
                Value = "Ingresó"
            },
            new SelectListItem
            {
                Text = "Se retiró",
                Value = "Se retiró"
            }
        };

        [BindProperty]
        [Required(ErrorMessage = "El campo Estado es requerido")]
        public string State { get; set; } = "Reservado";

        private readonly IMediator _mediator;

        public EditStatusModel(IMediator mediator)
        {
            _mediator = mediator;
        }

        [BindProperty]
        public GuestDetail GuestDetail { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }

            var guestDetail = await _mediator.Send(new GetGuestQuery(id.Value));
            if (guestDetail is null)
                return NotFound();

            GuestDetail = guestDetail;
            State = guestDetail.State;

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
                return Page();

            await _mediator.Send(new UpdateGuestStateCommand(GuestDetail.Id, State));

            return RedirectToPage("./Index");
        }
    }
}

src/UniqueFundraisingEvent/UniqueFundraisingEvent.Web/Pages/Guests/Index.cshtml.cs
using CsvHelper;
using CsvHelper.Configuration;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Globalization;
using UniqueFundraisingEvent.Web.Application.Contracts.Persistence;
using UniqueFundraisingEvent.Web.Application.Features.Guests.Commands.RegisterGuest;
using UniqueFundraisingEvent.Web.Application.Features.Guests.Queries.GetGuestsList;

namespace UniqueFundraisingEvent.Web.Pages.Guests
{
    public class GuestsModel : PageModel
    {
        private readonly IServiceProvider _serviceProvider;
        private readonly IMediator _mediator;

        [BindProperty]
        public IFormFile ImportUpload { get; set; } = default!;

        public IEnumerable<GuestInList> Guests { get; set; } = new List<GuestInList>();

        public GuestsModel(IServiceProvider serviceProvider, IMediator mediator)
        {
            _serviceProvider = serviceProvider;
            _mediator = mediator;
        }

        public async Task OnGet()
        {
            Guests = await _mediator.Send(new GetGuestsListQuery());
        }

        public async Task<IActionResult> OnPostImport()
        {
            using var memoryStream = new MemoryStream();
            await ImportUpload.CopyToAsync(memoryStream);

            memoryStream.Seek(0, SeekOrigin.Begin);

            var config = new CsvConfiguration(CultureInfo.InvariantCulture)
            {
                HasHeaderRecord = false
            };

            using var reader = new StreamReader(memoryStream);
            using var csv = new CsvReader(reader, config);
            var records = csv.GetRecords<RegisterGuestCommand>();

            var unitOfWork = _serviceProvider.GetRequiredService<UnitOfWork>();
            foreach (var record in records)
                await _mediator.Send(record);
            await unitOfWork.CommitAsync();

            return RedirectToPage("./Index");
        }
    }
}

src/UniqueFundraisingEvent/UniqueFundraisingEvent.Web/Pages/Guests/Create.cshtml
@page
@model CreateModel
@inject MetadataSettings metadataSettings

@{
    ViewData["Title"] = "Agregar invitado";
}

<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">@metadataSettings.ApplicationName</a></li>
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Evento</a></li>
                    <li class="breadcrumb-item active">Invitados</li>
                </ol>
            </div>
            <h4 class="page-title">@ViewData["Title"]</h4>
        </div>
    </div>
</div>
<!-- end page title -->

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    <div class="mb-3">
                        <div class="row">
                        <div class="col-xl-6">
                                <div class="mb-3">
                                    <select class="form-control select2" data-toggle="select2" asp-for="State" asp-items="@Model.States"></select>
                                </div>

                                <div class="mb-3">
                                    <input asp-for="Name" class="form-control" placeholder="Nombre" />
                                    <span asp-validation-for="Name" class="text-danger"></span>
                                </div>

                                <div class="mb-3">
                                    <input asp-for="LastName" class="form-control" placeholder="Apellidos" />
                                        <span asp-validation-for="LastName" class="text-danger"></span>
                                </div>

                                <div class="mb-3">
                                    <input asp-for="Email" class="form-control" placeholder="Correo" />
                                    <span asp-validation-for="Email" class="text-danger"></span>
                                </div>

                                <div class="mb-3">
                                    <input asp-for="Company" class="form-control" placeholder="Empresa" />
                                    <span asp-validation-for="Company" class="text-danger"></span>
                                </div>

                                <div class="mb-0">
                                    <input asp-for="CompanyPosition" class="form-control" placeholder="Cargo" />
                                    <span asp-validation-for="CompanyPosition" class="text-danger"></span>
                                </div>

                        </div> <!-- end col-->

                        <div class="col-xl-6">
                        </div> <!-- end col-->
                    </div>
                    </div>
                    <div class="d-flex flex-wrap gap-2">
                        <button type="submit" class="btn btn-primary">Guardar</button>
                        <a asp-page="Index" class="btn btn-link">Cancelar</a>
                    </div>
                </form>
            </div> <!-- end card-body -->
        </div> <!-- end card-->
    </div> <!-- end col-->
</div>
<!-- end row-->

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/UniqueFundraisingEvent/UniqueFundraisingEvent.Web/Pages/Guests/EditDonations.cshtml
@page
@model EditDonationsModel
@inject MetadataSettings metadataSettings

@{
    ViewData["Title"] = "Actualizar donación";
}

<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">@metadataSettings.ApplicationName</a></li>
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Evento</a></li>
                    <li class="breadcrumb-item active">Invitados</li>
                </ol>
            </div>
            <h4 class="page-title">@ViewData["Title"]</h4>
        </div>
    </div>
</div>
<!-- end page title -->

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    <div class="mb-3">
                        <div class="row">
                            <div class="col-xl-6">

                                <div class="mb-3">
                                    <input asp-for="GuestDetail.Id" class="form-control" type="hidden" />
                                </div>

                                <div class="mb-3">
                                    <input asp-for="GuestDetail.DonationAmount" class="form-control" placeholder="Donaci&oacute;n" />
                                    <span asp-validation-for="GuestDetail.DonationAmount" class="text-danger"></span>
                                </div>

                                <div class="mb-3">
                                    <input asp-for="GuestDetail.Name" class="form-control" disabled />
                                </div>

                                <div class="mb-3">
                                    <input asp-for="GuestDetail.LastName" class="form-control" disabled />
                                </div>

                                <div class="mb-3">
                                    <input asp-for="GuestDetail.Email" class="form-control" disabled />
                                </div>

                                <div class="mb-3">
                                    <input asp-for="GuestDetail.Company" class="form-control" disabled />
                                </div>

                                <div class="mb-0">
                                    <input asp-for="GuestDetail.CompanyPosition" class="form-control" disabled />
                                </div>

                            </div> <!-- end col-->

                            <div class="col-xl-6">
                            </div> <!-- end col-->
                        </div>
                    </div>
                    <div class="d-flex flex-wrap gap-2">
                        <button type="submit" class="btn btn-primary">Guardar</button>
                        <a asp-page="Index" class="btn btn-link">Cancelar</a>
                    </div>
                </form>
            </div> <!-- end card-body -->
        </div> <!-- end card-->
    </div> <!-- end col-->
</div>
<!-- end row-->
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

src/UniqueFundraisingEvent/UniqueFundraisingEvent.Web/Pages/Guests/EditStatus.cshtml
@page
@model EditStatusModel
@inject MetadataSettings metadataSettings

@{
    ViewData["Title"] = "Actualizar estado";
}

<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">@metadataSettings.ApplicationName</a></li>
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Evento</a></li>
                    <li class="breadcrumb-item active">Invitados</li>
                </ol>
            </div>
            <h4 class="page-title">@ViewData["Title"]</h4>
        </div>
    </div>
</div>
<!-- end page title -->

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    <div class="mb-3">
                        <div class="row">
                            <div class="col-xl-6">
                                <div class="mb-3">
                                    <select class="form-control select2" data-toggle="select2" asp-for="State" asp-items="@Model.States"></select>
                                </div>

                                <div class="mb-3">
                                    <input asp-for="GuestDetail.Name" class="form-control" placeholder="Nombre" disabled />
                                </div>

                                <div class="mb-3">
                                    <input asp-for="GuestDetail.LastName" class="form-control" placeholder="Apellidos" disabled />
                                </div>

                                <div class="mb-3">
                                    <input asp-for="GuestDetail.Email" class="form-control" placeholder="Correo" disabled />
                                </div>

                                <div class="mb-3">
                                    <input asp-for="GuestDetail.Company" class="form-control" placeholder="Empresa" disabled />
                                </div>

                                <div class="mb-0">
                                    <input asp-for="GuestDetail.CompanyPosition" class="form-control" placeholder="Cargo" disabled />
                                </div>

                            </div> <!-- end col-->

                            <div class="col-xl-6">
                            </div> <!-- end col-->
                        </div>
                    </div>
                    <div class="d-flex flex-wrap gap-2">
                        <button type="submit" class="btn btn-primary">Guardar</button>
                        <a asp-page="Index" class="btn btn-link">Cancelar</a>
                    </div>
                </form>
            </div> <!-- end card-body -->
        </div> <!-- end card-->
    </div> <!-- end col-->
</div>
<!-- end row-->
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

src/UniqueFundraisingEvent/UniqueFundraisingEvent.Web/Pages/Guests/Index.cshtml
@page "/"
@using System.Security.Claims;
@model GuestsModel
@inject MetadataSettings metadataSettings

@{
    ViewData["Title"] = "Invitados";
    var CurrentRole = User.FindFirst(ClaimTypes.Role).Value;
}

<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">@metadataSettings.ApplicationName</a></li>
                    <li class="breadcrumb-item"><a href="javascript: void(0);">Evento</a></li>
                    <li class="breadcrumb-item active">Invitados</li>
                </ol>
            </div>
            <h4 class="page-title">@ViewData["Title"]</h4>
        </div>
    </div>
</div>
<!-- end page title -->

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="row mb-2">
                    <div class="col-sm-5">
                        <a asp-page="Create" class="btn btn-primary mb-2"><i class="mdi mdi-plus-circle me-2"></i> Agregar invitado</a>
                    </div>
                    <div class="col-sm-7">
                        <div class="text-sm-end">
                            <form id="form-import" asp-page-handler="Import" method="post" enctype="multipart/form-data">
                                <input id="input-import" class="d-none" type="file" asp-for="ImportUpload" accept=".csv" onchange="document.getElementById('form-import').submit();" />
                                <button type="button" class="btn btn-light mb-2" onclick="document.getElementById('input-import').click()">Importar</button>
                            </form>
                        </div>
                    </div><!-- end col-->
                </div>

                <div class="table-responsive">
                    <table class="table table-centered w-100 dt-responsive nowrap" id="guests-datatable">
                        <thead class="bg-primary text-white">
                            <tr>
                                <th class="all">Nombre</th>
                                <th>Apellido</th>
                                <th>Correo</th>
                                <th>Empresa</th>
                                <th>Cargo</th>
                                <th>
                                    @if (CurrentRole == "Administrador" || CurrentRole == "Recolector")
                                    {
                                        <span>Donaci&oacute;n</span>
                                    }
                                </th>
                                <th>Estado</th>
                                <th style="width: 85px;">Acci&oacute;n</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var guest in Model.Guests)
                            {
                                <tr>
                                    <td>
                                        @guest.Name
                                    </td>
                                    <td>
                                        @guest.LastName
                                    </td>
                                    <td>
                                        @guest.Email
                                    </td>
                                    <td>
                                        @guest.Company
                                    </td>
                                    <td>
                                        @guest.CompanyPosition
                                    </td>
                                    <td>
                                        @if (CurrentRole == "Administrador" || CurrentRole == "Recolector")
                                        {
                                            <span>@guest.DonationAmount</span>
                                        }
                                    </td>
                                    <td>
                                        @if (guest.State == "Reservado")
                                        {
                                            <span class="badge bg-danger">@guest.State</span>
                                        }
                                        else if (guest.State == "Ingresó")
                                        {
                                            <span class="badge bg-success">@guest.State</span>
                                        }
                                        else
                                        {
                                            <span class="badge bg-warning">@guest.State</span>
                                        }
                                    </td>
                                    <td class="table-action">
                                        @if (CurrentRole == "Administrador" || CurrentRole == "Recolector")
                                        {
                                            <a asp-page="./EditDonations" asp-route-id="@guest.Id" class="action-icon"> <i class="mdi mdi-cash-multiple"></i></a>
                                        }
                                        @if (CurrentRole == "Administrador" || CurrentRole == "Recepcionista")
                                        {
                                            <a asp-page="./EditStatus" asp-route-id="@guest.Id" class="action-icon"> <i class="mdi mdi-playlist-check"></i></a>
                                        }
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div> <!-- end card-body-->
        </div> <!-- end card-->
    </div> <!-- end col -->
</div>
<!-- end row -->
@section Scripts {
    <script src="assets/js/pages/guests.index.js"></script>
}

@*<p>
    <a asp-page="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Guest[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Guest[0].LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Guest[0].Company)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Guest[0].CompanyPosition)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Guest[0].State)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Guest[0].DonationAmount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Guest[0].FechaCreacion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Guest)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Company)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CompanyPosition)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.State)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DonationAmount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaCreacion)
                </td>
                <td>
                    <a asp-page="./Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-page="./Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-page="./Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
*@